import type { Express } from "express";
import { createServer, type Server } from "http";
import bcrypt from "bcryptjs";
import { storage } from "./storage";
import { requireAuth, requireRole } from "./auth";
import {
  insertStudentSchema, insertTeacherSchema, insertCourseSchema,
  insertMarkSchema, insertAttendanceSchema, insertCourseEnrollmentSchema,
  insertUserSchema, insertAssignmentSchema, insertAssignmentSubmissionSchema,
  insertNotificationSchema, insertCalendarEventSchema,
  insertAnnouncementSchema, insertAnnouncementCommentSchema
} from "@shared/schema";
import { z } from "zod";

// Default password assigned to every teacher/student account created by an
// admin/teacher. The account is flagged mustChangePassword=true so the user is
// forced to set their own password the first time they log in.
const DEFAULT_ACCOUNT_PASSWORD = "changeme123";

// Validation schemas for auth
const loginSchema = z.object({
  // Accepts either an email address or a username in the same field.
  username: z.string().min(1, "Email or username is required"),
  password: z.string().min(1, "Password is required"),
  role: z.enum(['admin', 'teacher', 'student']).optional(),
});

const changePasswordSchema = z.object({
  currentPassword: z.string().optional(),
  newPassword: z.string().min(6, "New password must be at least 6 characters"),
});

// Simplified create schemas — only the essential fields are entered in the UI;
// everything else (IDs, dates, status) is generated by the server.
const createTeacherSchema = z.object({
  firstName: z.string().min(1, "First name is required"),
  lastName: z.string().min(1, "Last name is required"),
  email: z.string().email("A valid email is required"),
  subject: z.string().min(1, "Subject is required"),
  // Grades (classes) this teacher will teach — drives the teacher↔student link.
  grades: z.array(z.number().min(1).max(12)).min(1, "Select at least one grade"),
});

const createStudentSchema = z.object({
  firstName: z.string().min(1, "First name is required"),
  lastName: z.string().min(1, "Last name is required"),
  email: z.string().email("A valid email is required"),
  grade: z.number().min(1).max(12),
  section: z.string().min(1).max(10),
});

// Generate the next sequential business ID (e.g. TCH-0007 / STU-0301) by
// scanning the highest existing numeric suffix for the given prefix.
function nextSequentialId(prefix: string, existingIds: string[]): string {
  let max = 0;
  for (const id of existingIds) {
    const match = id?.match(new RegExp(`^${prefix}-(\\d+)$`));
    if (match) {
      const n = parseInt(match[1], 10);
      if (n > max) max = n;
    }
  }
  return `${prefix}-${String(max + 1).padStart(4, "0")}`;
}

const today = () => new Date().toISOString().split("T")[0];

// Resolve the teacher profile for the currently logged-in teacher session,
// trying profileId first (the correct link) and falling back to older shapes.
async function resolveSessionTeacher(session: any) {
  const searchId = session?.user?.profileId || session?.userId || "";
  if (!searchId) return null;
  let teacher = await storage.getTeacher(searchId);
  if (!teacher) teacher = await storage.getTeacherByTeacherId(searchId);
  return teacher || null;
}

// Resolve the student profile for the currently logged-in student session.
async function resolveSessionStudent(session: any) {
  const searchId = session?.user?.profileId || session?.userId || "";
  if (!searchId) return null;
  let student = await storage.getStudent(searchId);
  if (!student) student = await storage.getStudentByStudentId(searchId);
  return student || null;
}

// The set of course IDs a teacher owns (for scoping list/read/write access).
async function teacherCourseIdSet(session: any): Promise<Set<string>> {
  const teacher = await resolveSessionTeacher(session);
  if (!teacher) return new Set();
  const courses = await storage.getCoursesByTeacher(teacher.id);
  return new Set(courses.map(c => c.id));
}

// Create one course per assigned grade for a newly-created teacher, so they
// immediately have courses to attach assignments / marks / attendance to.
async function createCoursesForTeacher(
  teacher: { id: string; teacherId: string; subject: string },
  grades: number[]
) {
  const subjPrefix =
    (teacher.subject || "GEN").replace(/[^A-Za-z]/g, "").slice(0, 4).toUpperCase() || "GEN";
  const idPart = teacher.teacherId.replace(/[^A-Za-z0-9]/g, "");

  // Pre-fetch all students once so we can enroll each grade's existing students
  // into the course we create for it. This makes the teacher↔student link
  // order-independent: a student created *before* this teacher's course still
  // gets enrolled, so any assignment the teacher later posts reaches them.
  const allStudents = await storage.getAllStudents();

  for (const grade of grades) {
    try {
      const course = await storage.createCourse({
        courseCode: `${subjPrefix}-G${grade}-${idPart}`,
        name: `${teacher.subject} — Grade ${grade}`,
        description: `${teacher.subject} for Grade ${grade}`,
        grade,
        subject: teacher.subject,
        teacherId: teacher.id,
        credits: 4,
        status: "active",
      } as any);

      // Enroll every existing student of this grade into the new course.
      const gradeStudents = allStudents.filter(s => s.grade === grade);
      await Promise.all(
        gradeStudents.map(s =>
          storage
            .createCourseEnrollment({
              studentId: s.id,
              courseId: course.id,
              enrollmentDate: today(),
              status: "active",
            } as any)
            .catch(() => undefined) // ignore duplicate enrollments
        )
      );
    } catch (e) {
      // A duplicate course code is fine to ignore; anything else we log so it's
      // visible in the server console.
      if ((e as any)?.code !== '23505') {
        console.error(`[API] Failed to auto-create course for grade ${grade}:`, e);
      }
    }
  }
}

// Enroll a newly-created student into every course matching their grade, so they
// pick up that grade's teachers, assignments, marks and attendance context.
async function enrollStudentInGrade(studentId: string, grade: number) {
  const allCourses = await storage.getAllCourses();
  const gradeCourses = allCourses.filter(c => c.grade === grade);
  for (const c of gradeCourses) {
    try {
      await storage.createCourseEnrollment({
        studentId,
        courseId: c.id,
        enrollmentDate: today(),
        status: "active",
      } as any);
    } catch (e) {
      /* ignore duplicate enrollment */
    }
  }
}

// Map a set of student profile IDs to their login (users) IDs — notifications
// are addressed to the login account, which is what the client queries.
async function userIdsForStudentIds(studentIds: string[]): Promise<string[]> {
  if (studentIds.length === 0) return [];
  const wanted = new Set(studentIds);
  const users = await storage.getAllUsers();
  return users
    .filter(u => u.role === "student" && u.profileId && wanted.has(u.profileId))
    .map(u => u.id);
}

// Best-effort fan-out of an in-app notification to a set of users.
async function notifyUsers(
  userIds: string[],
  n: { title: string; message: string; type?: string; actionUrl?: string }
): Promise<void> {
  await Promise.all(
    userIds.map(uid =>
      storage
        .createNotification({
          userId: uid,
          title: n.title,
          message: n.message,
          type: (n.type as any) || "info",
          read: false,
          actionUrl: n.actionUrl,
        } as any)
        .catch(() => undefined)
    )
  );
}

// Resolve the display identity (id, name, role) of the currently logged-in user
// for stamping onto announcements and comments.
async function resolveAuthorIdentity(session: any): Promise<{
  authorId: string;
  authorName: string;
  authorRole: string;
} | null> {
  const userId = session?.userId;
  const role = session?.userRole;
  if (!userId || !role) return null;

  if (role === "admin") {
    return { authorId: userId, authorName: "Administrator", authorRole: "admin" };
  }
  if (role === "teacher") {
    const teacher = await resolveSessionTeacher(session);
    const name = teacher ? `${teacher.firstName} ${teacher.lastName}` : "Teacher";
    return { authorId: userId, authorName: name, authorRole: "teacher" };
  }
  if (role === "student") {
    const student = await resolveSessionStudent(session);
    const name = student ? `${student.firstName} ${student.lastName}` : "Student";
    return { authorId: userId, authorName: name, authorRole: "student" };
  }
  return { authorId: userId, authorName: "User", authorRole: role };
}

// The grades that determine which grade-targeted announcements a user can see.
// - teacher: the grades of the courses they teach
// - student: their own grade
// - admin: [] (admins see everything, handled separately)
async function gradesForSession(session: any): Promise<number[]> {
  const role = session?.userRole;
  if (role === "teacher") {
    const teacher = await resolveSessionTeacher(session);
    if (!teacher) return [];
    const courses = await storage.getCoursesByTeacher(teacher.id);
    return Array.from(new Set(courses.map(c => c.grade)));
  }
  if (role === "student") {
    const student = await resolveSessionStudent(session);
    return student ? [student.grade] : [];
  }
  return [];
}

export async function registerRoutes(app: Express): Promise<Server> {

  // ───────────────────── Authentication Routes ─────────────────────

  app.post("/api/auth/login", async (req, res) => {
    try {
      const { username, password, role } = loginSchema.parse(req.body);

      // Allow login by username OR email (teachers/students log in with the
      // email that was entered when their account was created).
      const identifier = username.trim();
      let user = await storage.getUserByUsername(identifier);
      if (!user) {
        user = await storage.getUserByEmail(identifier.toLowerCase());
      }
      if (!user) {
        return res.status(401).json({ message: "Invalid credentials" });
      }

      const isValid = await bcrypt.compare(password, user.password);
      if (!isValid) {
        return res.status(401).json({ message: "Invalid credentials" });
      }

      // Validate role if provided (for demo purposes, we allow login with selected role)
      // In production, this would be determined by the user's actual role
      if (role && role !== user.role) {
        // Allow demo login with different role for testing purposes
        // In production, this check should be removed or made more restrictive
        console.log(`[AUTH] Demo login: user '${username}' (role: ${user.role}) attempting to login as '${role}'`);
      }

      // Set session
      req.session.userId = user.id;
      req.session.userRole = user.role as 'admin' | 'teacher' | 'student';
      req.session.user = {
        id: user.id,
        username: user.username,
        email: user.email,
        role: user.role,
        profileId: user.profileId || undefined,
      };
      req.session.mustChangePassword = user.mustChangePassword;

      // Save session before responding
      req.session.save((err) => {
        if (err) {
          console.error('[AUTH] Session save error:', err);
          return res.status(500).json({ message: "Login failed" });
        }
        res.json({
          id: user.id,
          username: user.username,
          email: user.email,
          role: user.role,
          profileId: user.profileId,
          mustChangePassword: user.mustChangePassword,
          success: true,
        });
      });
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      console.error("[AUTH] Login error:", error);
      res.status(500).json({ message: "Login failed" });
    }
  });

  // Self-signup has been removed. Accounts are created only when an admin adds a
  // teacher or a teacher adds a student; those users log in with their email and
  // the default password, then must change it on first login (below).

  app.post("/api/auth/change-password", requireAuth, async (req, res) => {
    try {
      const { currentPassword, newPassword } = changePasswordSchema.parse(req.body);

      const user = await storage.getUser(req.session.userId!);
      if (!user) {
        return res.status(404).json({ message: "User not found" });
      }

      // If a current password is supplied (voluntary change), verify it.
      // On a forced first-login change the client may omit it.
      if (currentPassword) {
        const ok = await bcrypt.compare(currentPassword, user.password);
        if (!ok) {
          return res.status(400).json({ message: "Current password is incorrect" });
        }
      }

      const hashedPassword = await bcrypt.hash(newPassword, 12);
      await storage.updateUser(user.id, {
        password: hashedPassword,
        mustChangePassword: false,
      });

      req.session.mustChangePassword = false;
      res.json({ success: true, message: "Password changed successfully" });
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      console.error("[AUTH] Change password error:", error);
      res.status(500).json({ message: "Failed to change password" });
    }
  });

  app.post("/api/auth/logout", (req, res) => {
    // Clear all session data
    req.session.userId = undefined;
    req.session.userRole = undefined;
    req.session.user = undefined;
    
    req.session.destroy((err) => {
      if (err) {
        console.error('[AUTH] Logout error:', err);
        return res.status(500).json({ message: "Logout failed" });
      }
      res.clearCookie('connect.sid', { path: '/' });
      res.json({ message: "Logged out successfully" });
    });
  });

  app.get("/api/auth/me", (req, res) => {
    if (!req.session?.userId) {
      return res.status(401).json({ message: "Not authenticated" });
    }
    res.json({
      id: req.session.userId,
      role: req.session.userRole,
      profileId: req.session.user?.profileId,
      mustChangePassword: req.session.mustChangePassword ?? false,
    });
  });

  // ───────────────────── Student Routes ─────────────────────

  // Get all students - Admin sees all, Teacher sees enrolled students
  app.get("/api/students", requireAuth, async (req, res) => {
    try {
      const userId = req.session.userId;
      const userRole = req.session.userRole;
      const profileId = req.session.user?.profileId;

      if (!userId) {
        return res.status(401).json({ message: "Unauthorized" });
      }

      let students;

      // If teacher, filter by courses they teach
      if (userRole === 'teacher') {
        // First try to find teacher by profileId (this is the correct way)
        let teacher = profileId ? await storage.getTeacher(profileId) : null;
        
        // If not found by profileId, try by userId directly
        if (!teacher) {
          teacher = await storage.getTeacher(userId);
        }
        
        // If still not found, try to find teacher by teacherId (e.g., TCH-0001)
        if (!teacher) {
          teacher = await storage.getTeacherByTeacherId(userId);
        }
        
        // Last resort: find by matching with user profile
        if (!teacher) {
          const allTeachers = await storage.getAllTeachers();
          const allUsers = await storage.getAllUsers();
          const user = allUsers.find(u => u.id === userId || u.username === userId);
          if (user?.profileId) {
            teacher = allTeachers.find(t => t.id === user.profileId);
          }
        }

        if (!teacher) {
          return res.json([]);
        }

        const teacherIdToUse = teacher.id;
        const teacherCourses = await storage.getCoursesByTeacher(teacherIdToUse);
        const courseIds = teacherCourses.map(c => c.id);

        if (courseIds.length === 0) {
          // Teacher has no courses, return empty
          return res.json([]);
        }

        // Get enrollments for these courses
        const enrollments = await Promise.all(
          courseIds.map(cid => storage.getEnrollmentsByCourse(cid))
        );
        const studentIds = new Set(enrollments.flat().map(e => e.studentId));

        // Get only those students
        const allStudents = await storage.getAllStudents();
        students = allStudents.filter(s => studentIds.has(s.id));
      } else if (userRole === 'student') {
        // Students can only see their own profile
        const student = await storage.getStudentByStudentId(userId)
          || await storage.getStudent(userId);
        students = student ? [student] : [];
      } else {
        // Admin sees all
        students = await storage.getAllStudents();
      }

      res.json(students);
    } catch (error) {
      console.error("[API] Fetch students error:", error);
      res.status(500).json({ message: "Failed to fetch students" });
    }
  });

  app.get("/api/students/:id", requireAuth, async (req, res) => {
    try {
      const student = await storage.getStudent(req.params.id);
      if (!student) {
        return res.status(404).json({ message: "Student not found" });
      }
      res.json(student);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch student" });
    }
  });

  // Admins and teachers can add students. A linked login account (email +
  // default password) is created automatically; the student must change the
  // password on first login, and is auto-enrolled in their grade's courses.
  app.post("/api/students", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      const data = createStudentSchema.parse(req.body);
      const email = data.email.trim().toLowerCase();

      const existingUser = await storage.getUserByEmail(email);
      if (existingUser) {
        return res.status(409).json({ message: "An account with this email already exists" });
      }

      const allStudents = await storage.getAllStudents();
      const studentId = nextSequentialId("STU", allStudents.map(s => s.studentId));

      const student = await storage.createStudent({
        studentId,
        firstName: data.firstName,
        lastName: data.lastName,
        email,
        grade: data.grade,
        section: data.section,
        status: "active",
        enrollmentDate: today(),
      } as any);

      const hashedPassword = await bcrypt.hash(DEFAULT_ACCOUNT_PASSWORD, 12);
      await storage.createUser({
        username: email,
        email,
        password: hashedPassword,
        role: "student",
        profileId: student.id,
        status: "active",
        mustChangePassword: true,
      } as any);

      // Enroll into all courses for this student's grade so they see that grade's
      // teachers, assignments, marks and attendance.
      await enrollStudentInGrade(student.id, student.grade);

      res.status(201).json({
        ...student,
        loginEmail: email,
        defaultPassword: DEFAULT_ACCOUNT_PASSWORD,
      });
    } catch (error) {
      if (error instanceof z.ZodError) {
        console.error("[API] Student validation error:", error.errors);
        return res.status(400).json({
          message: "Validation error",
          errors: error.errors.map(e => ({ field: e.path.join('.'), message: e.message }))
        });
      }
      if ((error as any)?.code === '23505') {
        return res.status(409).json({ message: "A student or account with this email already exists" });
      }
      console.error("[API] Create student error:", error);
      res.status(500).json({ message: "Failed to create student" });
    }
  });

  app.put("/api/students/:id", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      const validatedData = insertStudentSchema.partial().parse(req.body);
      const student = await storage.updateStudent(req.params.id, validatedData);
      if (!student) {
        return res.status(404).json({ message: "Student not found" });
      }
      res.json(student);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      res.status(500).json({ message: "Failed to update student" });
    }
  });

  app.delete("/api/students/:id", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      const success = await storage.deleteStudent(req.params.id);
      if (!success) {
        return res.status(404).json({ message: "Student not found" });
      }
      res.json({ message: "Student deleted successfully" });
    } catch (error) {
      res.status(500).json({ message: "Failed to delete student" });
    }
  });

  // Get teachers for a specific student (based on course enrollment).
  // The :studentId param may be a students.id or the human student_id; resolve
  // it robustly, and make sure a student can only view their own teachers.
  app.get("/api/students/:studentId/teachers", requireAuth, async (req, res) => {
    try {
      const { studentId } = req.params;
      const userRole = req.session.userRole;
      const profileId = req.session.user?.profileId;

      let student = await storage.getStudent(studentId);
      if (!student) student = await storage.getStudentByStudentId(studentId);
      if (!student) {
        return res.status(404).json({ message: "Student not found" });
      }

      // A student may only view their own teachers.
      if (userRole === 'student' && student.id !== profileId) {
        return res.status(403).json({ message: "Access denied" });
      }

      const allTeachers = await storage.getAllTeachers();
      const allCourses = await storage.getAllCourses();
      const teacherIds = new Set<string>();

      // (1) Grade-based link: any teacher who owns a course for this student's
      // grade (a teacher's grades are represented by the courses we create for
      // them, so no separate column is needed).
      for (const c of allCourses) {
        if (c.grade === student.grade && c.teacherId) teacherIds.add(c.teacherId);
      }

      // (2) Enrollment-based link: teachers of the courses the student is
      // actually enrolled in (covers seeded data and explicit enrollments).
      const enrollments = await storage.getEnrollmentsByStudent(student.id);
      if (enrollments.length > 0) {
        const courseIds = new Set(enrollments.map(e => e.courseId));
        for (const c of allCourses) {
          if (courseIds.has(c.id) && c.teacherId) teacherIds.add(c.teacherId);
        }
      }

      const studentTeachers = allTeachers.filter(t => teacherIds.has(t.id));
      res.json(studentTeachers);
    } catch (error) {
      console.error("[API] Fetch student teachers error:", error);
      res.status(500).json({ message: "Failed to fetch teachers" });
    }
  });

  // ───────────────────── Teacher Routes ─────────────────────

  app.get("/api/teachers", requireAuth, async (req, res) => {
    try {
      const teachers = await storage.getAllTeachers();
      res.json(teachers);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch teachers" });
    }
  });

  app.get("/api/teachers/:id", requireAuth, async (req, res) => {
    try {
      const teacher = await storage.getTeacher(req.params.id);
      if (!teacher) {
        return res.status(404).json({ message: "Teacher not found" });
      }
      res.json(teacher);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch teacher" });
    }
  });

  // Admin adds a teacher. A linked login account (email + default password) is
  // created automatically; the teacher must change the password on first login.
  app.post("/api/teachers", requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const data = createTeacherSchema.parse(req.body);
      const email = data.email.trim().toLowerCase();

      const existingUser = await storage.getUserByEmail(email);
      if (existingUser) {
        return res.status(409).json({ message: "An account with this email already exists" });
      }

      const allTeachers = await storage.getAllTeachers();
      const teacherId = nextSequentialId("TCH", allTeachers.map(t => t.teacherId));

      const grades = Array.from(new Set(data.grades)).sort((a, b) => a - b);
      const teacher = await storage.createTeacher({
        teacherId,
        firstName: data.firstName,
        lastName: data.lastName,
        email,
        subject: data.subject,
        joinDate: today(),
        status: "active",
      } as any);

      const hashedPassword = await bcrypt.hash(DEFAULT_ACCOUNT_PASSWORD, 12);
      await storage.createUser({
        username: email,
        email,
        password: hashedPassword,
        role: "teacher",
        profileId: teacher.id,
        status: "active",
        mustChangePassword: true,
      } as any);

      // Give the teacher a course for each assigned grade so they can create
      // assignments, marks and attendance right away.
      await createCoursesForTeacher(
        { id: teacher.id, teacherId: teacher.teacherId, subject: teacher.subject },
        grades
      );

      res.status(201).json({
        ...teacher,
        loginEmail: email,
        defaultPassword: DEFAULT_ACCOUNT_PASSWORD,
      });
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({
          message: "Validation error",
          errors: error.errors.map(e => ({ field: e.path.join('.'), message: e.message })),
        });
      }
      if ((error as any)?.code === '23505') {
        return res.status(409).json({ message: "A teacher or account with this email already exists" });
      }
      console.error("[API] Create teacher error:", error);
      res.status(500).json({ message: "Failed to create teacher" });
    }
  });

  app.put("/api/teachers/:id", requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const validatedData = insertTeacherSchema.partial().parse(req.body);
      const teacher = await storage.updateTeacher(req.params.id, validatedData);
      if (!teacher) {
        return res.status(404).json({ message: "Teacher not found" });
      }
      res.json(teacher);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      res.status(500).json({ message: "Failed to update teacher" });
    }
  });

  app.delete("/api/teachers/:id", requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const success = await storage.deleteTeacher(req.params.id);
      if (!success) {
        return res.status(404).json({ message: "Teacher not found" });
      }
      res.json({ message: "Teacher deleted successfully" });
    } catch (error) {
      res.status(500).json({ message: "Failed to delete teacher" });
    }
  });

  // ───────────────────── Course Routes ─────────────────────

  app.get("/api/courses", requireAuth, async (req, res) => {
    try {
      const { grade, teacherId } = req.query;
      const role = req.session.userRole;
      let courses;

      if (grade) {
        courses = await storage.getCoursesByGrade(parseInt(grade as string));
      } else if (teacherId) {
        courses = await storage.getCoursesByTeacher(teacherId as string);
      } else if (role === 'teacher') {
        // A teacher sees only their own courses (resolved server-side so it does
        // not depend on any client-side id).
        const teacher = await resolveSessionTeacher(req.session);
        courses = teacher ? await storage.getCoursesByTeacher(teacher.id) : [];
      } else if (role === 'student') {
        // A student sees the courses they're enrolled in.
        const student = await resolveSessionStudent(req.session);
        if (student) {
          const enrollments = await storage.getEnrollmentsByStudent(student.id);
          const courseIds = new Set(enrollments.map(e => e.courseId));
          courses = (await storage.getAllCourses()).filter(c => courseIds.has(c.id));
        } else {
          courses = [];
        }
      } else {
        courses = await storage.getAllCourses();
      }

      res.json(courses);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch courses" });
    }
  });

  app.get("/api/courses/:id", requireAuth, async (req, res) => {
    try {
      const course = await storage.getCourse(req.params.id);
      if (!course) {
        return res.status(404).json({ message: "Course not found" });
      }
      res.json(course);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch course" });
    }
  });

  app.post("/api/courses", requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const validatedData = insertCourseSchema.parse(req.body);
      // Empty teacherId from the form means "unassigned" — store null, not "".
      if (!validatedData.teacherId) {
        (validatedData as any).teacherId = null;
      }
      const course = await storage.createCourse(validatedData);
      res.status(201).json(course);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      if ((error as any)?.code === '23505') {
        return res.status(409).json({ message: "A course with this course code already exists" });
      }
      console.error("[API] Create course error:", error);
      res.status(500).json({ message: "Failed to create course" });
    }
  });

  app.put("/api/courses/:id", requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const validatedData = insertCourseSchema.partial().parse(req.body);
      const course = await storage.updateCourse(req.params.id, validatedData);
      if (!course) {
        return res.status(404).json({ message: "Course not found" });
      }
      res.json(course);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      res.status(500).json({ message: "Failed to update course" });
    }
  });

  app.delete("/api/courses/:id", requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const success = await storage.deleteCourse(req.params.id);
      if (!success) {
        return res.status(404).json({ message: "Course not found" });
      }
      res.json({ message: "Course deleted successfully" });
    } catch (error) {
      res.status(500).json({ message: "Failed to delete course" });
    }
  });

  // ───────────────────── Mark Routes ─────────────────────

  app.get("/api/marks", requireAuth, async (req, res) => {
    try {
      const { studentId, courseId } = req.query;
      const role = req.session.userRole;
      let marks;

      if (studentId) {
        marks = await storage.getMarksByStudent(studentId as string);
      } else if (courseId) {
        marks = await storage.getMarksByCourse(courseId as string);
      } else {
        marks = await storage.getAllMarks();
      }

      // Role scoping: teachers see only their courses' marks; students only own.
      if (role === 'teacher') {
        const courseIds = await teacherCourseIdSet(req.session);
        marks = marks.filter(m => courseIds.has(m.courseId));
      } else if (role === 'student') {
        const student = await resolveSessionStudent(req.session);
        marks = student ? marks.filter(m => m.studentId === student.id) : [];
      }

      res.json(marks);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch marks" });
    }
  });

  app.post("/api/marks", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      const validatedData = insertMarkSchema.parse(req.body);

      // Teachers may only enter marks for courses they teach.
      if (req.session.userRole === 'teacher') {
        const courseIds = await teacherCourseIdSet(req.session);
        if (!courseIds.has(validatedData.courseId)) {
          return res.status(403).json({ message: "You can only enter marks for your own courses" });
        }
      }

      const mark = await storage.createMark(validatedData);
      res.status(201).json(mark);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      res.status(500).json({ message: "Failed to create mark" });
    }
  });

  app.put("/api/marks/:id", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      const existing = await storage.getMark(req.params.id);
      if (!existing) {
        return res.status(404).json({ message: "Mark not found" });
      }
      if (req.session.userRole === 'teacher') {
        const courseIds = await teacherCourseIdSet(req.session);
        if (!courseIds.has(existing.courseId)) {
          return res.status(403).json({ message: "You can only edit marks for your own courses" });
        }
      }

      const validatedData = insertMarkSchema.partial().parse(req.body);
      const mark = await storage.updateMark(req.params.id, validatedData);
      if (!mark) {
        return res.status(404).json({ message: "Mark not found" });
      }
      res.json(mark);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      res.status(500).json({ message: "Failed to update mark" });
    }
  });

  app.delete("/api/marks/:id", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      const existing = await storage.getMark(req.params.id);
      if (!existing) {
        return res.status(404).json({ message: "Mark not found" });
      }
      if (req.session.userRole === 'teacher') {
        const courseIds = await teacherCourseIdSet(req.session);
        if (!courseIds.has(existing.courseId)) {
          return res.status(403).json({ message: "You can only delete marks for your own courses" });
        }
      }

      const success = await storage.deleteMark(req.params.id);
      if (!success) {
        return res.status(404).json({ message: "Mark not found" });
      }
      res.json({ message: "Mark deleted successfully" });
    } catch (error) {
      res.status(500).json({ message: "Failed to delete mark" });
    }
  });

  // ───────────────────── Attendance Routes ─────────────────────

  app.get("/api/attendance", requireAuth, async (req, res) => {
    try {
      const { studentId, courseId } = req.query;
      const role = req.session.userRole;
      let attendance;

      if (studentId) {
        attendance = await storage.getAttendanceByStudent(studentId as string);
      } else if (courseId) {
        attendance = await storage.getAttendanceByCourse(courseId as string);
      } else {
        attendance = await storage.getAllAttendance();
      }

      // Role scoping: teachers see only their courses' records; students own.
      if (role === 'teacher') {
        const courseIds = await teacherCourseIdSet(req.session);
        attendance = attendance.filter(a => courseIds.has(a.courseId));
      } else if (role === 'student') {
        const student = await resolveSessionStudent(req.session);
        attendance = student ? attendance.filter(a => a.studentId === student.id) : [];
      }

      res.json(attendance);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch attendance" });
    }
  });

  // Get students for attendance - with proper filtering (not fetching all at once)
  app.get("/api/attendance/students", requireAuth, async (req, res) => {
    try {
      const userId = req.session.userId || '';
      const userRole = req.session.userRole;
      const profileId = req.session.user?.profileId;
      const grade = req.query.grade ? parseInt(req.query.grade as string) : null;
      const courseId = req.query.courseId as string | undefined;
      
      let students;
      
      if (userRole === 'admin') {
        // Admin can see all students filtered by grade/course
        students = await storage.getAllStudents();
        if (grade) {
          students = students.filter(s => s.grade === grade);
        }
        if (courseId) {
          const enrollments = await storage.getEnrollmentsByCourse(courseId);
          const studentIds = enrollments.map(e => e.studentId);
          students = students.filter(s => studentIds.includes(s.id));
        }
      } else if (userRole === 'teacher') {
        // Teacher sees students in their courses only
        const searchId = profileId || userId;
        let teacher = await storage.getTeacher(searchId);
        if (!teacher) teacher = await storage.getTeacherByTeacherId(searchId);
        
        if (teacher) {
          const teacherCourses = await storage.getCoursesByTeacher(teacher.id);
          let courseIds = teacherCourses.map(c => c.id);
          
          // If specific course selected, only that course
          if (courseId && courseIds.includes(courseId)) {
            courseIds = [courseId];
          }
          
          // Get enrollments for these courses
          const enrollments = await Promise.all(
            courseIds.map(cid => storage.getEnrollmentsByCourse(cid))
          );
          const studentIds = [...new Set(enrollments.flat().map(e => e.studentId))];
          
          students = await storage.getAllStudents();
          students = students.filter(s => studentIds.includes(s.id));
          
          // Filter by grade if specified
          if (grade) {
            students = students.filter(s => s.grade === grade);
          }
        } else {
          students = [];
        }
      } else if (userRole === 'student') {
        // Students can only see themselves
        const searchId = profileId || userId;
        let student = await storage.getStudent(searchId);
        if (!student) student = await storage.getStudentByStudentId(searchId);
        students = student ? [student] : [];
      } else {
        students = [];
      }
      
      res.json(students);
    } catch (error) {
      console.error("[API] Fetch attendance students error:", error);
      res.status(500).json({ message: "Failed to fetch students" });
    }
  });

  app.post("/api/attendance", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      const validatedData = insertAttendanceSchema.parse(req.body);

      // Teachers may only mark attendance for their own courses.
      if (req.session.userRole === 'teacher') {
        const courseIds = await teacherCourseIdSet(req.session);
        if (!courseIds.has(validatedData.courseId)) {
          return res.status(403).json({ message: "You can only mark attendance for your own courses" });
        }
      }

      const att = await storage.createAttendance(validatedData);
      res.status(201).json(att);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      res.status(500).json({ message: "Failed to create attendance" });
    }
  });

  app.put("/api/attendance/:id", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      const existing = await storage.getAttendance(req.params.id);
      if (!existing) {
        return res.status(404).json({ message: "Attendance not found" });
      }
      if (req.session.userRole === 'teacher') {
        const courseIds = await teacherCourseIdSet(req.session);
        if (!courseIds.has(existing.courseId)) {
          return res.status(403).json({ message: "You can only edit attendance for your own courses" });
        }
      }

      const validatedData = insertAttendanceSchema.partial().parse(req.body);
      const att = await storage.updateAttendance(req.params.id, validatedData);
      if (!att) {
        return res.status(404).json({ message: "Attendance not found" });
      }
      res.json(att);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      res.status(500).json({ message: "Failed to update attendance" });
    }
  });

  // ───────────────────── Enrollment Routes ─────────────────────

  app.get("/api/enrollments", requireAuth, async (req, res) => {
    try {
      const { studentId, courseId } = req.query;
      const role = req.session.userRole;
      let enrollments;

      if (studentId) {
        enrollments = await storage.getEnrollmentsByStudent(studentId as string);
      } else if (courseId) {
        enrollments = await storage.getEnrollmentsByCourse(courseId as string);
      } else {
        enrollments = await storage.getAllCourseEnrollments();
      }

      // Role scoping: teachers see only enrollments in their courses; students own.
      if (role === 'teacher') {
        const courseIds = await teacherCourseIdSet(req.session);
        enrollments = enrollments.filter(e => courseIds.has(e.courseId));
      } else if (role === 'student') {
        const student = await resolveSessionStudent(req.session);
        enrollments = student ? enrollments.filter(e => e.studentId === student.id) : [];
      }

      res.json(enrollments);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch enrollments" });
    }
  });

  app.post("/api/enrollments", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      const validatedData = insertCourseEnrollmentSchema.parse(req.body);
      const enrollment = await storage.createCourseEnrollment(validatedData);
      res.status(201).json(enrollment);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      res.status(500).json({ message: "Failed to create enrollment" });
    }
  });

  // ───────────────────── User Routes (Admin Only) ─────────────────────

  app.get("/api/users", requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const users = await storage.getAllUsers();
      // Never send passwords to the client
      res.json(users.map(user => ({ ...user, password: undefined })));
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch users" });
    }
  });

  app.post("/api/users", requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const validatedData = insertUserSchema.parse(req.body);
      const hashedPassword = await bcrypt.hash(validatedData.password, 12);
      const user = await storage.createUser({ ...validatedData, password: hashedPassword });
      res.status(201).json({ ...user, password: undefined });
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      res.status(500).json({ message: "Failed to create user" });
    }
  });

  // ───────────────────── Assignment Routes ─────────────────────

  app.get("/api/assignments", requireAuth, async (req, res) => {
    try {
      const userId = req.session.userId;
      const userRole = req.session.userRole;
      const profileId = req.session.user?.profileId;
      
      const allAssignments = await storage.getAllAssignments();
      
      // Filter based on role
      let assignments;
      
      if (userRole === 'admin') {
        // Admin sees all
        assignments = allAssignments;
      } else if (userRole === 'teacher') {
        // Teacher sees their own assignments
        let teacher = profileId ? await storage.getTeacher(profileId) : null;
        if (!teacher) teacher = await storage.getTeacher(userId);
        if (!teacher) teacher = await storage.getTeacherByTeacherId(userId);
        
        if (teacher) {
          assignments = allAssignments.filter(a => a.teacherId === teacher!.id);
        } else {
          assignments = [];
        }
      } else if (userRole === 'student') {
        // Student sees assignments for courses they're enrolled in
        let student = profileId ? await storage.getStudent(profileId) : null;
        if (!student) student = await storage.getStudent(userId);
        if (!student) student = await storage.getStudentByStudentId(userId);
        
        if (student) {
          // Get enrolled courses
          const enrollments = await storage.getEnrollmentsByStudent(student.id);
          const courseIds = enrollments.map(e => e.courseId);
          
          // Filter assignments for enrolled courses
          assignments = allAssignments.filter(a => courseIds.includes(a.courseId));
        } else {
          assignments = [];
        }
      } else {
        assignments = [];
      }
      
      res.json(assignments);
    } catch (error) {
      console.error("[API] Fetch assignments error:", error);
      res.status(500).json({ message: "Failed to fetch assignments" });
    }
  });

  app.get("/api/assignments/teacher/:teacherId", requireAuth, async (req, res) => {
    try {
      const assignments = await storage.getAssignmentsByTeacher(req.params.teacherId);
      res.json(assignments);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch teacher assignments" });
    }
  });

  app.get("/api/assignments/course/:courseId", requireAuth, async (req, res) => {
    try {
      const assignments = await storage.getAssignmentsByCourse(req.params.courseId);
      res.json(assignments);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch course assignments" });
    }
  });

  app.post("/api/assignments", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      // Shared notify helper for a freshly-created assignment.
      const notifyForAssignment = async (assignment: any) => {
        try {
          const enrollments = await storage.getEnrollmentsByCourse(assignment.courseId);
          const userIds = await userIdsForStudentIds(enrollments.map(e => e.studentId));
          await notifyUsers(userIds, {
            title: "New assignment posted",
            message: `${assignment.title} — due ${assignment.dueDate}`,
            type: "info",
            actionUrl: "/student-panel",
          });
        } catch (e) {
          console.error("[API] Assignment notification error:", e);
        }
      };

      if (req.session.userRole === 'teacher') {
        // The teacher does NOT pick a course — the assignment is created
        // automatically for every course (class) the teacher teaches.
        const teacher = await resolveSessionTeacher(req.session);
        if (!teacher) {
          return res.status(403).json({ message: "Teacher profile not found" });
        }
        let teacherCourses = await storage.getCoursesByTeacher(teacher.id);

        // Self-heal: if this teacher has no class yet (e.g. created before
        // grade-linking), give them a default course now so posting always
        // works, and enroll that grade's students so they receive it.
        if (teacherCourses.length === 0) {
          const defaultGrade = 10;
          const subjPrefix =
            (teacher.subject || "GEN").replace(/[^A-Za-z]/g, "").slice(0, 4).toUpperCase() || "GEN";
          const idPart = teacher.teacherId.replace(/[^A-Za-z0-9]/g, "");
          await storage.createCourse({
            courseCode: `${subjPrefix}-G${defaultGrade}-${idPart}`,
            name: `${teacher.subject} — Grade ${defaultGrade}`,
            description: `${teacher.subject} for Grade ${defaultGrade}`,
            grade: defaultGrade,
            subject: teacher.subject,
            teacherId: teacher.id,
            credits: 4,
            status: "active",
          } as any);
          teacherCourses = await storage.getCoursesByTeacher(teacher.id);

          const gradeStudents = (await storage.getAllStudents()).filter(s => s.grade === defaultGrade);
          for (const c of teacherCourses) {
            await Promise.all(
              gradeStudents.map(s =>
                storage
                  .createCourseEnrollment({ studentId: s.id, courseId: c.id, enrollmentDate: today(), status: "active" } as any)
                  .catch(() => undefined)
              )
            );
          }
        }

        const base = {
          title: req.body.title,
          description: req.body.description ?? null,
          dueDate: req.body.dueDate,
          totalPoints: typeof req.body.totalPoints === 'number' ? req.body.totalPoints : 100,
          type: req.body.type ?? 'assignment',
          status: req.body.status ?? 'active',
          createdAt: req.body.createdAt ?? today(),
          teacherId: teacher.id,
        };

        const created: any[] = [];
        for (const course of teacherCourses) {
          const validated = insertAssignmentSchema.parse({ ...base, courseId: course.id });
          const assignment = await storage.createAssignment(validated);
          created.push(assignment);
          await notifyForAssignment(assignment);
        }
        return res.status(201).json(created[0]);
      }

      // Admin path: courseId comes from the request body.
      const validatedData = insertAssignmentSchema.parse(req.body);
      const assignment = await storage.createAssignment(validatedData);
      await notifyForAssignment(assignment);
      res.status(201).json(assignment);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      console.error("[API] Create assignment error:", error);
      res.status(500).json({ message: "Failed to create assignment" });
    }
  });

  app.put("/api/assignments/:id", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      const existing = await storage.getAssignment(req.params.id);
      if (!existing) {
        return res.status(404).json({ message: "Assignment not found" });
      }
      if (req.session.userRole === 'teacher') {
        const teacher = await resolveSessionTeacher(req.session);
        if (!teacher || existing.teacherId !== teacher.id) {
          return res.status(403).json({ message: "You can only modify your own assignments" });
        }
      }

      const validatedData = insertAssignmentSchema.partial().parse(req.body);
      const assignment = await storage.updateAssignment(req.params.id, validatedData);
      if (!assignment) {
        return res.status(404).json({ message: "Assignment not found" });
      }
      res.json(assignment);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      res.status(500).json({ message: "Failed to update assignment" });
    }
  });

  app.delete("/api/assignments/:id", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      const existing = await storage.getAssignment(req.params.id);
      if (!existing) {
        return res.status(404).json({ message: "Assignment not found" });
      }
      if (req.session.userRole === 'teacher') {
        const teacher = await resolveSessionTeacher(req.session);
        if (!teacher || existing.teacherId !== teacher.id) {
          return res.status(403).json({ message: "You can only delete your own assignments" });
        }
      }

      const success = await storage.deleteAssignment(req.params.id);
      if (!success) {
        return res.status(404).json({ message: "Assignment not found" });
      }
      res.json({ message: "Assignment deleted successfully" });
    } catch (error) {
      res.status(500).json({ message: "Failed to delete assignment" });
    }
  });

  // ───────────────────── Assignment Submission Routes ─────────────────────

  // Get all submissions (filtered by role)
  app.get("/api/assignment-submissions", requireAuth, async (req, res) => {
    try {
      const userId = req.session.userId || '';
      const userRole = req.session.userRole;
      const profileId = req.session.user?.profileId;
      
      const allSubmissions = await storage.getAllAssignmentSubmissions();
      let submissions: typeof allSubmissions = [];
      
      if (userRole === 'admin') {
        // Admin sees all
        submissions = allSubmissions;
      } else if (userRole === 'teacher') {
        // Teacher sees submissions for assignments belonging to their courses.
        const teacher = await resolveSessionTeacher(req.session);
        if (teacher) {
          const teacherCourses = await storage.getCoursesByTeacher(teacher.id);
          const courseIds = new Set(teacherCourses.map(c => c.id));
          const allAssignments = await storage.getAllAssignments();
          const teacherAssignmentIds = new Set(
            allAssignments.filter(a => courseIds.has(a.courseId)).map(a => a.id)
          );
          submissions = allSubmissions.filter(s => teacherAssignmentIds.has(s.assignmentId));
        }
      } else if (userRole === 'student') {
        // Student sees their own submissions
        const searchId = profileId || userId;
        let student = await storage.getStudent(searchId);
        if (!student) student = await storage.getStudentByStudentId(searchId);
        
        if (student) {
          submissions = allSubmissions.filter(s => s.studentId === student!.id);
        }
      }
      
      res.json(submissions);
    } catch (error) {
      console.error("[API] Fetch submissions error:", error);
      res.status(500).json({ message: "Failed to fetch submissions" });
    }
  });

  app.get("/api/assignment-submissions/student/:studentId", requireAuth, async (req, res) => {
    try {
      const submissions = await storage.getSubmissionsByStudent(req.params.studentId);
      res.json(submissions);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch student submissions" });
    }
  });

  app.get("/api/assignment-submissions/assignment/:assignmentId", requireAuth, async (req, res) => {
    try {
      const submissions = await storage.getSubmissionsByAssignment(req.params.assignmentId);
      res.json(submissions);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch assignment submissions" });
    }
  });

  app.post("/api/assignment-submissions", requireAuth, async (req, res) => {
    try {
      const validatedData = insertAssignmentSubmissionSchema.parse(req.body);
      const submission = await storage.createAssignmentSubmission(validatedData);
      res.status(201).json(submission);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      res.status(500).json({ message: "Failed to create submission" });
    }
  });

  app.put("/api/assignment-submissions/:id", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      const existing = await storage.getAssignmentSubmission(req.params.id);
      if (!existing) {
        return res.status(404).json({ message: "Submission not found" });
      }

      // A teacher may only grade submissions for their own courses' assignments.
      let gradedByTeacherId: string | undefined;
      if (req.session.userRole === 'teacher') {
        const teacher = await resolveSessionTeacher(req.session);
        const assignment = existing.assignmentId
          ? await storage.getAssignment(existing.assignmentId)
          : undefined;
        const course = assignment?.courseId
          ? await storage.getCourse(assignment.courseId)
          : undefined;
        if (!teacher || !course || course.teacherId !== teacher.id) {
          return res.status(403).json({ message: "You can only grade submissions for your own courses" });
        }
        gradedByTeacherId = teacher.id;
      }

      const validatedData = insertAssignmentSubmissionSchema.partial().parse(req.body);

      // When a grade is supplied, stamp grading metadata server-side.
      if (validatedData.grade !== undefined && validatedData.grade !== null) {
        (validatedData as any).status = "graded";
        (validatedData as any).gradedAt = new Date().toISOString();
        if (gradedByTeacherId) (validatedData as any).gradedBy = gradedByTeacherId;
      }

      const submission = await storage.updateAssignmentSubmission(req.params.id, validatedData);
      if (!submission) {
        return res.status(404).json({ message: "Submission not found" });
      }

      // Notify the student when their submission is graded.
      if (validatedData.grade !== undefined && validatedData.grade !== null) {
        try {
          const userIds = await userIdsForStudentIds([submission.studentId]);
          const assignment = existing.assignmentId
            ? await storage.getAssignment(existing.assignmentId)
            : undefined;
          await notifyUsers(userIds, {
            title: "Assignment graded",
            message: `${assignment?.title ?? "Your assignment"} — grade: ${validatedData.grade}`,
            type: "success",
            actionUrl: "/student-panel",
          });
        } catch (e) {
          console.error("[API] Grade notification error:", e);
        }
      }

      res.json(submission);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      console.error("[API] Update submission error:", error);
      res.status(500).json({ message: "Failed to update submission" });
    }
  });

  // ───────────────────── Analytics Routes ─────────────────────

  app.get("/api/analytics/students-gpa", requireAuth, async (req, res) => {
    try {
      const studentsWithGPA = await storage.getStudentsWithGPA();
      res.json(studentsWithGPA);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch student GPA data" });
    }
  });

  app.get("/api/analytics/subject-toppers", requireAuth, async (req, res) => {
    try {
      const subjectToppers = await storage.getSubjectToppers();
      res.json(subjectToppers);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch subject toppers" });
    }
  });

  app.get("/api/analytics/attendance-stats", requireAuth, async (req, res) => {
    try {
      const attendanceStats = await storage.getAttendanceStats();
      res.json(attendanceStats);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch attendance stats" });
    }
  });

  app.get("/api/analytics/dashboard-stats", requireAuth, async (req, res) => {
    try {
      const [students, teachers, courses, attendanceStats] = await Promise.all([
        storage.getAllStudents(),
        storage.getAllTeachers(),
        storage.getAllCourses(),
        storage.getAttendanceStats()
      ]);

      const stats = {
        totalStudents: students.length,
        activeTeachers: teachers.filter(t => t.status === 'active').length,
        totalCourses: courses.filter(c => c.status === 'active').length,
        avgAttendance: attendanceStats.percentage
      };

      res.json(stats);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch dashboard stats" });
    }
  });

  // ───────────────────── Notification Routes ─────────────────────

  app.get("/api/notifications/:userId", requireAuth, async (req, res) => {
    try {
      const notifications = await storage.getNotificationsByUser(req.params.userId);
      res.json(notifications);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch notifications" });
    }
  });

  app.post("/api/notifications", requireAuth, async (req, res) => {
    try {
      const validatedData = insertNotificationSchema.parse(req.body);
      const notification = await storage.createNotification(validatedData);
      res.status(201).json(notification);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      res.status(500).json({ message: "Failed to create notification" });
    }
  });

  app.patch("/api/notifications/:id/read", requireAuth, async (req, res) => {
    try {
      const notification = await storage.markNotificationAsRead(req.params.id);
      if (!notification) {
        return res.status(404).json({ message: "Notification not found" });
      }
      res.json(notification);
    } catch (error) {
      res.status(500).json({ message: "Failed to update notification" });
    }
  });

  app.delete("/api/notifications/:id", requireAuth, async (req, res) => {
    try {
      const success = await storage.deleteNotification(req.params.id);
      if (!success) {
        return res.status(404).json({ message: "Notification not found" });
      }
      res.json({ message: "Notification deleted successfully" });
    } catch (error) {
      res.status(500).json({ message: "Failed to delete notification" });
    }
  });

  // ───────────────────── Announcement Routes ─────────────────────

  // List announcements the current user is allowed to see, each with its
  // comments embedded. Visibility:
  //   - admin:   every announcement
  //   - teacher: "everyone" posts + posts for grades they teach + their own posts
  //   - student: "everyone" posts + posts for their grade
  app.get("/api/announcements", requireAuth, async (req, res) => {
    try {
      const role = req.session.userRole;
      const userId = req.session.userId || "";

      let visible;
      if (role === "admin") {
        visible = await storage.getAllAnnouncements();
      } else {
        const grades = await gradesForSession(req.session);
        visible = await storage.getAnnouncementsForGrades(grades);
        // A teacher should always see their own posts, even if targeted at a
        // grade they no longer teach.
        if (role === "teacher") {
          const own = (await storage.getAllAnnouncements()).filter(a => a.authorId === userId);
          const seen = new Set(visible.map(a => a.id));
          for (const a of own) {
            if (!seen.has(a.id)) visible.push(a);
          }
          visible.sort((a, b) =>
            new Date(b.createdAt as any).getTime() - new Date(a.createdAt as any).getTime()
          );
        }
      }

      // Embed comments (single query for all visible announcements).
      const ids = visible.map(a => a.id);
      const comments = await storage.getCommentsForAnnouncements(ids);
      const byAnnouncement = new Map<string, typeof comments>();
      for (const c of comments) {
        if (!byAnnouncement.has(c.announcementId)) byAnnouncement.set(c.announcementId, []);
        byAnnouncement.get(c.announcementId)!.push(c);
      }

      const result = visible.map(a => ({
        ...a,
        comments: byAnnouncement.get(a.id) || [],
      }));

      res.json(result);
    } catch (error) {
      console.error("[API] Fetch announcements error:", error);
      res.status(500).json({ message: "Failed to fetch announcements" });
    }
  });

  // Create an announcement (admins and teachers).
  app.post("/api/announcements", requireAuth, requireRole("admin", "teacher"), async (req, res) => {
    try {
      const data = insertAnnouncementSchema.parse(req.body);
      const identity = await resolveAuthorIdentity(req.session);
      if (!identity) {
        return res.status(403).json({ message: "Could not resolve your account" });
      }

      const targetGrade = data.targetGrade ?? null;

      // A teacher may target "everyone" or a grade they teach — not other grades.
      if (req.session.userRole === "teacher" && targetGrade !== null) {
        const grades = await gradesForSession(req.session);
        if (!grades.includes(targetGrade)) {
          return res.status(403).json({
            message: "You can only post announcements to grades you teach (or to everyone).",
          });
        }
      }

      const announcement = await storage.createAnnouncement({
        title: data.title,
        content: data.content,
        targetGrade,
        authorId: identity.authorId,
        authorName: identity.authorName,
        authorRole: identity.authorRole,
      } as any);

      // Best-effort notify the targeted students.
      try {
        const allStudents = await storage.getAllStudents();
        const targetStudents = targetGrade === null
          ? allStudents
          : allStudents.filter(s => s.grade === targetGrade);
        const userIds = await userIdsForStudentIds(targetStudents.map(s => s.id));
        await notifyUsers(userIds, {
          title: "New announcement",
          message: announcement.title,
          type: "info",
          actionUrl: "/announcements",
        });
      } catch (e) {
        console.error("[API] Announcement notification error:", e);
      }

      res.status(201).json({ ...announcement, comments: [] });
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      console.error("[API] Create announcement error:", error);
      res.status(500).json({ message: "Failed to create announcement" });
    }
  });

  // Delete an announcement (admin: any; teacher: only their own).
  app.delete("/api/announcements/:id", requireAuth, requireRole("admin", "teacher"), async (req, res) => {
    try {
      const existing = await storage.getAnnouncement(req.params.id);
      if (!existing) {
        return res.status(404).json({ message: "Announcement not found" });
      }
      if (req.session.userRole === "teacher" && existing.authorId !== req.session.userId) {
        return res.status(403).json({ message: "You can only delete your own announcements" });
      }
      await storage.deleteAnnouncement(req.params.id);
      res.json({ message: "Announcement deleted successfully" });
    } catch (error) {
      console.error("[API] Delete announcement error:", error);
      res.status(500).json({ message: "Failed to delete announcement" });
    }
  });

  // Add a comment to an announcement (any authenticated user who can see it).
  app.post("/api/announcements/:id/comments", requireAuth, async (req, res) => {
    try {
      const announcement = await storage.getAnnouncement(req.params.id);
      if (!announcement) {
        return res.status(404).json({ message: "Announcement not found" });
      }

      // Enforce visibility: a non-admin can only comment on announcements they
      // are allowed to see.
      const role = req.session.userRole;
      if (role !== "admin") {
        const grades = await gradesForSession(req.session);
        const isEveryone = announcement.targetGrade === null;
        const inGrade = announcement.targetGrade !== null && grades.includes(announcement.targetGrade);
        const isOwn = announcement.authorId === req.session.userId;
        if (!isEveryone && !inGrade && !isOwn) {
          return res.status(403).json({ message: "You cannot comment on this announcement" });
        }
      }

      const data = insertAnnouncementCommentSchema.parse(req.body);
      const identity = await resolveAuthorIdentity(req.session);
      if (!identity) {
        return res.status(403).json({ message: "Could not resolve your account" });
      }

      const comment = await storage.createAnnouncementComment({
        announcementId: announcement.id,
        content: data.content,
        authorId: identity.authorId,
        authorName: identity.authorName,
        authorRole: identity.authorRole,
      } as any);

      // Notify the announcement's author when someone else comments.
      if (announcement.authorId !== identity.authorId) {
        await notifyUsers([announcement.authorId], {
          title: "New comment on your announcement",
          message: `${identity.authorName} commented on "${announcement.title}"`,
          type: "info",
          actionUrl: "/announcements",
        }).catch(() => undefined);
      }

      res.status(201).json(comment);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      console.error("[API] Create comment error:", error);
      res.status(500).json({ message: "Failed to add comment" });
    }
  });

  // Delete a comment (admin: any; comment author: own; announcement author:
  // moderation on their own announcement).
  app.delete("/api/announcements/:id/comments/:commentId", requireAuth, async (req, res) => {
    try {
      const comment = await storage.getAnnouncementComment(req.params.commentId);
      if (!comment) {
        return res.status(404).json({ message: "Comment not found" });
      }

      const role = req.session.userRole;
      const userId = req.session.userId;
      let allowed = role === "admin" || comment.authorId === userId;

      if (!allowed) {
        const announcement = await storage.getAnnouncement(comment.announcementId);
        if (announcement && announcement.authorId === userId) allowed = true;
      }

      if (!allowed) {
        return res.status(403).json({ message: "You cannot delete this comment" });
      }

      await storage.deleteAnnouncementComment(req.params.commentId);
      res.json({ message: "Comment deleted successfully" });
    } catch (error) {
      console.error("[API] Delete comment error:", error);
      res.status(500).json({ message: "Failed to delete comment" });
    }
  });

  // Calendar Routes

  // Get calendar events with role-based filtering
  app.get("/api/calendar/events", requireAuth, async (req, res) => {
    try {
      const { year, month } = req.query;
      const userRole = req.session.userRole;
      const userId = req.session.userId;

      let events;

      if (year && month) {
        events = await storage.getCalendarEventsByMonth(
          parseInt(year as string),
          parseInt(month as string)
        );
      } else {
        events = await storage.getAllCalendarEvents();
      }

      // Filter events based on role
      let filteredEvents = events;
      
      if (userRole === 'teacher') {
        // Teachers see: global events (no grade) + events for their courses' grades
        const teacher = await resolveSessionTeacher(req.session);
        const teacherCourses = teacher ? await storage.getCoursesByTeacher(teacher.id) : [];
        const teacherGrades: number[] = [];
        teacherCourses.forEach(c => {
          if (!teacherGrades.includes(c.grade)) teacherGrades.push(c.grade);
        });

        filteredEvents = events.filter(event => {
          // Include global events (no grade specified)
          if (!event.grade) return true;
          // Include events for teacher's grades
          if (teacherGrades.includes(event.grade)) return true;
          return false;
        });
      } else if (userRole === 'student') {
        // Students see: global events + events for their enrolled courses' grades
        const profileId = req.session.user?.profileId;
        let student = profileId ? await storage.getStudent(profileId) : undefined;
        if (!student && userId) student = await storage.getStudent(userId);
        const enrollments = student ? await storage.getEnrollmentsByStudent(student.id) : [];
        const studentCourseIds = enrollments.map(e => e.courseId);
        const allCourses = await storage.getAllCourses();
        const studentCourses = allCourses.filter(c => studentCourseIds.includes(c.id));
        const studentGrades: number[] = [];
        studentCourses.forEach(c => {
          if (!studentGrades.includes(c.grade)) studentGrades.push(c.grade);
        });

        filteredEvents = events.filter(event => {
          // Include global events (no grade specified)
          if (!event.grade) return true;
          // Include events for student's grades
          if (studentGrades.includes(event.grade)) return true;
          return false;
        });
      }
      // Admin sees all events

      res.json(filteredEvents);
    } catch (error) {
      console.error("[API] Fetch calendar events error:", error);
      res.status(500).json({ message: "Failed to fetch calendar events" });
    }
  });

  app.get("/api/calendar/events/:id", requireAuth, async (req, res) => {
    try {
      const event = await storage.getCalendarEvent(req.params.id);
      if (!event) {
        return res.status(404).json({ message: "Event not found" });
      }
      res.json(event);
    } catch (error) {
      res.status(500).json({ message: "Failed to fetch event" });
    }
  });

  app.post("/api/calendar/events", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      const userId = req.session.userId;
      const userRole = req.session.userRole;
      const validatedData = insertCalendarEventSchema.parse(req.body);

      // If teacher, they can only create events for their courses or grades
      if (userRole === 'teacher') {
        const teacher = await resolveSessionTeacher(req.session);
        const teacherCourses = teacher ? await storage.getCoursesByTeacher(teacher.id) : [];
        const teacherGrades: number[] = [];
        teacherCourses.forEach(c => {
          if (!teacherGrades.includes(c.grade)) teacherGrades.push(c.grade);
        });

        // If grade is specified, must be one of teacher's grades
        // If no grade (global event), deny for teachers
        if (validatedData.grade && !teacherGrades.includes(validatedData.grade)) {
          return res.status(403).json({ message: "You can only create events for your assigned grades" });
        }
        if (!validatedData.grade) {
          return res.status(403).json({ message: "Teachers cannot create global events. Please specify a grade." });
        }
      }

      const event = await storage.createCalendarEvent({
        ...validatedData,
        createdBy: userId,
      });
      res.status(201).json(event);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      console.error("[API] Create calendar event error:", error);
      res.status(500).json({ message: "Failed to create event" });
    }
  });

  app.put("/api/calendar/events/:id", requireAuth, requireRole('admin', 'teacher'), async (req, res) => {
    try {
      const validatedData = insertCalendarEventSchema.partial().parse(req.body);
      const event = await storage.updateCalendarEvent(req.params.id, validatedData);
      if (!event) {
        return res.status(404).json({ message: "Event not found" });
      }
      res.json(event);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ message: "Validation error", errors: error.errors });
      }
      res.status(500).json({ message: "Failed to update event" });
    }
  });

  app.delete("/api/calendar/events/:id", requireAuth, requireRole('admin'), async (req, res) => {
    try {
      const success = await storage.deleteCalendarEvent(req.params.id);
      if (!success) {
        return res.status(404).json({ message: "Event not found" });
      }
      res.json({ message: "Event deleted successfully" });
    } catch (error) {
      res.status(500).json({ message: "Failed to delete event" });
    }
  });

  const httpServer = createServer(app);
  return httpServer;
}
